In [1]:
import ee
import ee.deserializer
import geemap
import json
import os

import geopandas as gpd

from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

C:\Users\lain\Documents\AFOLU\.venv\Lib\site-packages\geemap\conversion.py:23: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

True

In [11]:
df_oceans = gpd.read_file(r"C:\Users\lain\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Natural Oceans\ne_10m_ocean.shp").to_crs("EPSG:4326")["geometry"].item()
df_bbox = gpd.read_file(r"C:\Users\lain\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\afolu_resources\generated\small\bbox\shapely\GUY+Georgetown.gpkg")["geometry"].item()

In [10]:
df_oceans

,featurecla,scalerank,min_zoom,geometry
0,Ocean,0,0,"MULTIPOLYGON (((59.91603 -67.40049, 59.67856 -..."

In [9]:
df_bbox.overlay(df_oceans, how="difference")

                                            geometry
0  POLYGON ((-58.31593 6.6261, -58.32107 6.63336,...